#!/usr/bin/python3
from raubase_ros.plan import BehaviourPlan
from rclpy import init, ok, spin_once, shutdown
import matplotlib.pyplot as plt
from raubase_ros.calib import WheelMaddahi, LineSensor

WIDTH = 45


class CalibrationTool(BehaviourPlan):
    def __init__(self) -> None:
        super().__init__("calibration_tool")
        self.task: str = self.declare_wparameter("task", "none").get()

    def print_header(self) -> None:
        self.get_logger().info("".center(WIDTH, "="))
        self.get_logger().info("Raubase Calibration Tool".center(WIDTH, " "))
        self.get_logger().info("".center(WIDTH, "="))

    def parse_param(self) -> None:
        match self.task:
            case "wheel" | "maddahi":
                self.get_logger().info(
                    "Running calibration for wheel with the Maddahi methods"
                )
                self.add_task(WheelMaddahi())
            case "line":
                self.get_logger().info("Running calibration for line sensors")
                self.add_task(LineSensor())
            case _:
                self.get_logger().warn(f"No calibration choosen ({self.task})")
                self.done = True
        self.reinitialize()


if __name__ == "__main__":
    init()

    plt.ion()
    node = CalibrationTool()

    if not node.done:
        node.print_header()
    node.parse_param()

    while ok() and not node.done:
        first = False
        spin_once(node)
        plt.pause(0.001)

    input("Press [enter] to close all windows")

    shutdown()
